apiVersion: v1
kind: Service
metadata:
  name: analytics-worker
  namespace: swiftpay
  labels: { app.kubernetes.io/name: analytics-worker, app.kubernetes.io/part-of: swiftpay }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: analytics-worker }
  ports:
    - { name: http, port: 8083, targetPort: 8083 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-worker
  namespace: swiftpay
  labels: { app.kubernetes.io/name: analytics-worker, app.kubernetes.io/part-of: swiftpay }
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: analytics-worker }
  template:
    metadata:
      labels: { app.kubernetes.io/name: analytics-worker, app.kubernetes.io/part-of: swiftpay }
    spec:
      containers:
        - name: analytics-worker
          image: swiftpay/analytics-worker:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - { containerPort: 8083, name: http }
          env:
            - { name: SPRING_PROFILES_ACTIVE,    value: kubernetes }
            - { name: SERVER_PORT,               value: "8083" }
            - { name: KAFKA_BOOTSTRAP_SERVERS,   value: "kafka.swiftpay.svc.cluster.local:9092" }
            - { name: POSTGRES_HOST,             value: "postgres.swiftpay.svc.cluster.local" }
            - { name: POSTGRES_PORT,             value: "5432" }
            - { name: POSTGRES_DB,               value: "swiftpay_analytics" }
            - { name: POSTGRES_USER,             value: "mahipaul" }
            - { name: POSTGRES_PASSWORD,         value: "12345678" }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8083 }
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8083 }
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests: { memory: 384Mi, cpu: 100m  }
            limits:   { memory: 1Gi,   cpu: 1500m }
