apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: swiftpay
  labels: { app.kubernetes.io/name: ledger-service, app.kubernetes.io/part-of: swiftpay }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: ledger-service }
  ports:
    - { name: http, port: 8082, targetPort: 8082 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: swiftpay
  labels: { app.kubernetes.io/name: ledger-service, app.kubernetes.io/part-of: swiftpay }
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: ledger-service }
  template:
    metadata:
      labels: { app.kubernetes.io/name: ledger-service, app.kubernetes.io/part-of: swiftpay }
    spec:
      containers:
        - name: ledger-service
          image: swiftpay/ledger-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - { containerPort: 8082, name: http }
          env:
            - { name: SPRING_PROFILES_ACTIVE,    value: kubernetes }
            - { name: SERVER_PORT,               value: "8082" }
            - { name: KAFKA_BOOTSTRAP_SERVERS,   value: "kafka.swiftpay.svc.cluster.local:9092" }
            - { name: POSTGRES_HOST,             value: "postgres.swiftpay.svc.cluster.local" }
            - { name: POSTGRES_PORT,             value: "5432" }
            - { name: POSTGRES_DB,               value: "swiftpay_ledger" }
            - { name: POSTGRES_USER,             value: "mahipaul" }
            - { name: POSTGRES_PASSWORD,         value: "12345678" }
            - { name: REDIS_HOST,                value: "redis.swiftpay.svc.cluster.local" }
            - { name: REDIS_PORT,                value: "6379" }
            - { name: REDIS_USERNAME,            value: "myuser" }
            - { name: REDIS_PASSWORD,            value: "MyNewStr0ngPass!" }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            initialDelaySeconds: 90
            periodSeconds: 30
          resources:
            requests: { memory: 512Mi, cpu: 200m  }
            limits:   { memory: 1Gi,   cpu: 1500m }
